import fs from 'node:fs/promises';
import path from 'node:path';
import { existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const PROJECT_ROOT = path.resolve(__dirname, '../..');
const COMPONENTS_DIR = path.join(PROJECT_ROOT, 'src', 'components');
const COMPONENT_INDEX_PATH = path.join(COMPONENTS_DIR, 'index.ts');

const usage = () =>
  `Usage:\nnode ./scripts/ui-generator/cleanup.mjs \\
  --prefix AutoGenerated \\
  [--name ComponentName] [--dry-run] [--force]\n\n` +
  `If --name is omitted, all components starting with --prefix are removed.\n` +
  `Default prefix: AutoGenerated.\n` +
  `Use --force to actually delete files; otherwise this is a safety check.\n` +
  `Use --dry-run to preview before delete.`;

const normalizeArgKey = value =>
  value.replace(/^--/, '').replace(/-([a-z])/g, (_, ch) => ch.toUpperCase());

const parseArgs = argv => {
  const options = {
    force: false,
    dryRun: false,
    prefix: 'AutoGenerated',
    names: [],
    help: false,
  };

  for (let index = 0; index < argv.length; index += 1) {
    const rawArg = argv[index];
    if (!rawArg?.startsWith('--')) {
      continue;
    }

    const boolKeys = ['force', 'dryRun', 'help'];
    const [rawKey, inlineValue] = rawArg.includes('=')
      ? rawArg.split('=', 2)
      : [rawArg, undefined];
    const key = normalizeArgKey(rawKey);

    if (boolKeys.includes(key)) {
      options[key] = true;
      continue;
    }

    const value = inlineValue ?? argv[index + 1];
    if (!value) {
      throw new Error(`Missing value for ${rawArg}`);
    }

    if (inlineValue === undefined) {
      index += 1;
    }

    if (key === 'name') {
      options.names.push(value);
      continue;
    }

    if (key === 'prefix') {
      options.prefix = value;
      continue;
    }

    options[key] = value;
  }

  return options;
};

const toPascalCase = value =>
  `${value}`
    .replace(/[-_]/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');

const collectTargetsByPrefix = async prefix => {
  const entries = await fs.readdir(COMPONENTS_DIR, { withFileTypes: true });
  return entries
    .filter(entry => entry.isDirectory() && entry.name.startsWith(prefix))
    .map(entry => entry.name);
};

const removeExportFromBarrel = async componentNames => {
  const current = await fs.readFile(COMPONENT_INDEX_PATH, 'utf8');
  const filtered = current
    .split('\n')
    .filter(line => {
      const trimmed = line.trim();
      return !componentNames.some(name =>
        new RegExp(`^export\\s+\\*\\s+from\\s+'\\./${name}';$`).test(trimmed),
      );
    })
    .filter(Boolean)
    .join('\n');

  if (filtered !== current.trim()) {
    await fs.writeFile(COMPONENT_INDEX_PATH, `${filtered.trim()}\n`);
  }
};

const confirm = targets => {
  console.log('Preview of components to remove:');
  targets.forEach(name => {
    console.log(`- ${name}`);
  });
  console.log('');
  throw new Error('Use --force to actually perform cleanup.');
};

const main = async () => {
  const options = parseArgs(process.argv.slice(2));

  if (options.help) {
    console.log(usage());
    return;
  }

  const selected = new Set(options.names.map(name => toPascalCase(name)));
  if (selected.size === 0 && options.prefix) {
    const byPrefix = await collectTargetsByPrefix(options.prefix);
    byPrefix.forEach(name => selected.add(name));
  }

  if (selected.size === 0) {
    throw new Error('No matching component directories found.');
  }

  const targets = [...selected];

  if (!options.force && !options.dryRun) {
    return confirm(targets);
  }

  if (options.dryRun) {
    console.log('Dry-run mode enabled. Nothing deleted.');
    targets.forEach(name => {
      const targetDir = path.join(COMPONENTS_DIR, name);
      console.log(
        `${existsSync(targetDir) ? '[exists]' : '[missing]'} ${targetDir}`,
      );
    });
    return;
  }

  await Promise.all(
    targets.map(name =>
      fs.rm(path.join(COMPONENTS_DIR, name), { recursive: true, force: true }),
    ),
  );

  await removeExportFromBarrel(targets);
  console.log(`Removed component directories: ${targets.join(', ')}`);
  console.log('Updated src/components/index.ts');
};

main().catch(error => {
  console.error(error?.message || error);
  process.exitCode = 1;
});
