import type { OrgChartNodeData, OrgChartNodeAccent } from './types';

const createNode = (
  id: string,
  parentId: string | null,
  name: string,
  position: string,
  companyCode: string,
  location: string,
  headcount: string,
  accent: OrgChartNodeAccent,
): OrgChartNodeData => ({
  id,
  parentId,
  name,
  position,
  companyCode,
  location,
  headcount,
  accent,
});

export const companyHierarchy20Data: OrgChartNodeData[] = [
  createNode(
    '1',
    null,
    'Blueprint Global Group',
    'Holding Group',
    'BGG-HQ',
    'Dubai, UAE',
    '14.2k',
    'primary',
  ),
  createNode(
    '2',
    '1',
    'MENA Platforms',
    'Regional Platform',
    'MENA-01',
    'Dubai, UAE',
    '3.8k',
    'primary',
  ),
  createNode(
    '3',
    '1',
    'European Ventures',
    'Regional Platform',
    'EU-02',
    'Amsterdam, NL',
    '2.9k',
    'info',
  ),
  createNode(
    '4',
    '1',
    'APAC Holdings',
    'Regional Platform',
    'APAC-03',
    'Singapore, SG',
    '4.1k',
    'success',
  ),
  createNode(
    '5',
    '1',
    'Americas Network',
    'Regional Platform',
    'AMER-04',
    'New York, US',
    '3.4k',
    'warning',
  ),
  createNode(
    '6',
    '2',
    'Gulf Payments',
    'Operating Company',
    'MENA-GP',
    'Riyadh, SA',
    '1.1k',
    'primary',
  ),
  createNode(
    '7',
    '2',
    'Levant Commerce',
    'Operating Company',
    'MENA-LC',
    'Amman, JO',
    '860',
    'primary',
  ),
  createNode(
    '8',
    '3',
    'Alpine Mobility',
    'Operating Company',
    'EU-AM',
    'Munich, DE',
    '940',
    'info',
  ),
  createNode(
    '9',
    '3',
    'Iberia Logistics',
    'Operating Company',
    'EU-IL',
    'Madrid, ES',
    '780',
    'info',
  ),
  createNode(
    '10',
    '4',
    'India Finserv',
    'Operating Company',
    'APAC-IF',
    'Bengaluru, IN',
    '1.4k',
    'success',
  ),
  createNode(
    '11',
    '4',
    'Southeast Retail',
    'Operating Company',
    'APAC-SR',
    'Kuala Lumpur, MY',
    '980',
    'success',
  ),
  createNode(
    '12',
    '5',
    'Atlantic Health',
    'Operating Company',
    'AMER-AH',
    'Boston, US',
    '920',
    'warning',
  ),
  createNode(
    '13',
    '5',
    'Pacific Cloud',
    'Operating Company',
    'AMER-PC',
    'Vancouver, CA',
    '1.1k',
    'warning',
  ),
  createNode(
    '14',
    '6',
    'Riyadh Digital Bank',
    'Business Unit',
    'GP-RDB',
    'Riyadh, SA',
    '460',
    'primary',
  ),
  createNode(
    '15',
    '6',
    'Abu Dhabi Wallet',
    'Business Unit',
    'GP-ADW',
    'Abu Dhabi, UAE',
    '380',
    'primary',
  ),
  createNode(
    '16',
    '7',
    'Amman Marketplaces',
    'Business Unit',
    'LC-AMK',
    'Amman, JO',
    '290',
    'primary',
  ),
  createNode(
    '17',
    '8',
    'Munich Fleet Systems',
    'Business Unit',
    'AM-MFS',
    'Munich, DE',
    '310',
    'info',
  ),
  createNode(
    '18',
    '10',
    'Bengaluru Credit Works',
    'Business Unit',
    'IF-BCW',
    'Bengaluru, IN',
    '520',
    'success',
  ),
  createNode(
    '19',
    '10',
    'Mumbai Treasury Services',
    'Business Unit',
    'IF-MTS',
    'Mumbai, IN',
    '340',
    'success',
  ),
  createNode(
    '20',
    '13',
    'Toronto Data Infrastructure',
    'Business Unit',
    'PC-TDI',
    'Toronto, CA',
    '410',
    'warning',
  ),
];

export const companyHierarchy50Data: OrgChartNodeData[] = [
  createNode(
    '1',
    null,
    'Blueprint Global Group',
    'Holding Group',
    'BGG-HQ',
    'Dubai, UAE',
    '36.8k',
    'primary',
  ),
  createNode(
    '2',
    '1',
    'Middle East Portfolio',
    'Regional Platform',
    'ME-01',
    'Dubai, UAE',
    '7.6k',
    'primary',
  ),
  createNode(
    '3',
    '1',
    'Africa Portfolio',
    'Regional Platform',
    'AF-02',
    'Nairobi, KE',
    '4.9k',
    'info',
  ),
  createNode(
    '4',
    '1',
    'Europe Portfolio',
    'Regional Platform',
    'EU-03',
    'Amsterdam, NL',
    '6.8k',
    'success',
  ),
  createNode(
    '5',
    '1',
    'Asia Pacific Portfolio',
    'Regional Platform',
    'APAC-04',
    'Singapore, SG',
    '9.4k',
    'warning',
  ),
  createNode(
    '6',
    '1',
    'Americas Portfolio',
    'Regional Platform',
    'AMER-05',
    'New York, US',
    '8.1k',
    'danger',
  ),
  createNode(
    '7',
    '2',
    'Gulf Financial Services',
    'Operating Company',
    'ME-GFS',
    'Riyadh, SA',
    '1.8k',
    'primary',
  ),
  createNode(
    '8',
    '2',
    'Arabia Commerce Group',
    'Operating Company',
    'ME-ACG',
    'Jeddah, SA',
    '1.3k',
    'primary',
  ),
  createNode(
    '9',
    '2',
    'Levant Infrastructure',
    'Operating Company',
    'ME-LIN',
    'Amman, JO',
    '980',
    'primary',
  ),
  createNode(
    '10',
    '3',
    'East Africa Health',
    'Operating Company',
    'AF-EAH',
    'Nairobi, KE',
    '1.4k',
    'info',
  ),
  createNode(
    '11',
    '3',
    'West Africa Logistics',
    'Operating Company',
    'AF-WAL',
    'Accra, GH',
    '1.1k',
    'info',
  ),
  createNode(
    '12',
    '4',
    'Nordic Energy Systems',
    'Operating Company',
    'EU-NES',
    'Stockholm, SE',
    '1.2k',
    'success',
  ),
  createNode(
    '13',
    '4',
    'Central Europe Mobility',
    'Operating Company',
    'EU-CEM',
    'Munich, DE',
    '1.5k',
    'success',
  ),
  createNode(
    '14',
    '4',
    'Southern Europe Retail',
    'Operating Company',
    'EU-SER',
    'Madrid, ES',
    '1.1k',
    'success',
  ),
  createNode(
    '15',
    '5',
    'India Finserv Network',
    'Operating Company',
    'AP-IFN',
    'Bengaluru, IN',
    '2.1k',
    'warning',
  ),
  createNode(
    '16',
    '5',
    'Southeast Consumer Brands',
    'Operating Company',
    'AP-SCB',
    'Kuala Lumpur, MY',
    '1.8k',
    'warning',
  ),
  createNode(
    '17',
    '5',
    'Oceania Data Systems',
    'Operating Company',
    'AP-ODS',
    'Sydney, AU',
    '1.4k',
    'warning',
  ),
  createNode(
    '18',
    '6',
    'North America Health',
    'Operating Company',
    'AM-NAH',
    'Boston, US',
    '1.9k',
    'danger',
  ),
  createNode(
    '19',
    '6',
    'Latin Commerce Group',
    'Operating Company',
    'AM-LCG',
    'Mexico City, MX',
    '1.3k',
    'danger',
  ),
  createNode(
    '20',
    '6',
    'Pacific Infrastructure',
    'Operating Company',
    'AM-PIN',
    'Vancouver, CA',
    '1.6k',
    'danger',
  ),
  createNode(
    '21',
    '7',
    'Riyadh Treasury Hub',
    'Business Unit',
    'GFS-RTH',
    'Riyadh, SA',
    '420',
    'primary',
  ),
  createNode(
    '22',
    '7',
    'Doha Merchant Services',
    'Business Unit',
    'GFS-DMS',
    'Doha, QA',
    '380',
    'primary',
  ),
  createNode(
    '23',
    '8',
    'Jeddah Marketplace Stack',
    'Business Unit',
    'ACG-JMS',
    'Jeddah, SA',
    '340',
    'primary',
  ),
  createNode(
    '24',
    '8',
    'Bahrain Seller Network',
    'Business Unit',
    'ACG-BSN',
    'Manama, BH',
    '290',
    'primary',
  ),
  createNode(
    '25',
    '9',
    'Jordan Cloud Core',
    'Business Unit',
    'LIN-JCC',
    'Amman, JO',
    '310',
    'primary',
  ),
  createNode(
    '26',
    '10',
    'Kenya Care Network',
    'Business Unit',
    'EAH-KCN',
    'Nairobi, KE',
    '360',
    'info',
  ),
  createNode(
    '27',
    '10',
    'Uganda Clinical Systems',
    'Business Unit',
    'EAH-UCS',
    'Kampala, UG',
    '280',
    'info',
  ),
  createNode(
    '28',
    '11',
    'Accra Freight Grid',
    'Business Unit',
    'WAL-AFG',
    'Accra, GH',
    '330',
    'info',
  ),
  createNode(
    '29',
    '11',
    'Lagos Port Analytics',
    'Business Unit',
    'WAL-LPA',
    'Lagos, NG',
    '350',
    'info',
  ),
  createNode(
    '30',
    '12',
    'Stockholm Grid Labs',
    'Business Unit',
    'NES-SGL',
    'Stockholm, SE',
    '300',
    'success',
  ),
  createNode(
    '31',
    '13',
    'Munich Fleet Cloud',
    'Business Unit',
    'CEM-MFC',
    'Munich, DE',
    '390',
    'success',
  ),
  createNode(
    '32',
    '13',
    'Prague Transit Ops',
    'Business Unit',
    'CEM-PTO',
    'Prague, CZ',
    '260',
    'success',
  ),
  createNode(
    '33',
    '14',
    'Madrid Store Platform',
    'Business Unit',
    'SER-MSP',
    'Madrid, ES',
    '280',
    'success',
  ),
  createNode(
    '34',
    '14',
    'Lisbon Delivery Grid',
    'Business Unit',
    'SER-LDG',
    'Lisbon, PT',
    '240',
    'success',
  ),
  createNode(
    '35',
    '15',
    'Bengaluru Credit Works',
    'Business Unit',
    'IFN-BCW',
    'Bengaluru, IN',
    '520',
    'warning',
  ),
  createNode(
    '36',
    '15',
    'Mumbai Treasury Services',
    'Business Unit',
    'IFN-MTS',
    'Mumbai, IN',
    '410',
    'warning',
  ),
  createNode(
    '37',
    '16',
    'Jakarta Retail Core',
    'Business Unit',
    'SCB-JRC',
    'Jakarta, ID',
    '390',
    'warning',
  ),
  createNode(
    '38',
    '16',
    'Bangkok Brand Studio',
    'Business Unit',
    'SCB-BBS',
    'Bangkok, TH',
    '310',
    'warning',
  ),
  createNode(
    '39',
    '17',
    'Sydney Edge Compute',
    'Business Unit',
    'ODS-SEC',
    'Sydney, AU',
    '340',
    'warning',
  ),
  createNode(
    '40',
    '17',
    'Melbourne Cloud Fabric',
    'Business Unit',
    'ODS-MCF',
    'Melbourne, AU',
    '260',
    'warning',
  ),
  createNode(
    '41',
    '18',
    'Boston Care Platform',
    'Business Unit',
    'NAH-BCP',
    'Boston, US',
    '430',
    'danger',
  ),
  createNode(
    '42',
    '18',
    'Chicago Benefits Engine',
    'Business Unit',
    'NAH-CBE',
    'Chicago, US',
    '320',
    'danger',
  ),
  createNode(
    '43',
    '19',
    'Mexico Merchant Stack',
    'Business Unit',
    'LCG-MMS',
    'Mexico City, MX',
    '360',
    'danger',
  ),
  createNode(
    '44',
    '19',
    'Bogota Seller Ops',
    'Business Unit',
    'LCG-BSO',
    'Bogota, CO',
    '250',
    'danger',
  ),
  createNode(
    '45',
    '20',
    'Toronto Data Fabric',
    'Business Unit',
    'PIN-TDF',
    'Toronto, CA',
    '380',
    'danger',
  ),
  createNode(
    '46',
    '20',
    'Seattle Infra Core',
    'Business Unit',
    'PIN-SIC',
    'Seattle, US',
    '340',
    'danger',
  ),
  createNode(
    '47',
    '21',
    'Treasury AI Desk',
    'Brand Unit',
    'RTH-AI',
    'Riyadh, SA',
    '120',
    'primary',
  ),
  createNode(
    '48',
    '23',
    'Marketplace Seller Suite',
    'Brand Unit',
    'JMS-MSS',
    'Jeddah, SA',
    '110',
    'primary',
  ),
  createNode(
    '49',
    '26',
    'Clinical Partner Cloud',
    'Brand Unit',
    'KCN-CPC',
    'Nairobi, KE',
    '95',
    'info',
  ),
  createNode(
    '50',
    '30',
    'Smart Grid Research',
    'Brand Unit',
    'SGL-SGR',
    'Stockholm, SE',
    '105',
    'success',
  ),
];

export const initialData = companyHierarchy20Data;
